### ISSUE TITLE
Full run stops after 60 records

### ISSUE THREAD

**Issue by akshay7chauhan** [prashantghimire/sofifa-web-scraper#17]
<img width="1440" alt="Screenshot 2024-05-13 at 12 36 33 PM" src="https://github.com/prashantghimire/sofifa-web-scraper/assets/41875622/fca83226-ca40-456c-abb2-61498c2ceb80">

**Comment by prashantghimire** [comment]
@akshay7chauhan sorry i missed that in the readme file. you should run `npm run download-urls` before running `npm run full`.
<img width="673" alt="image" src="https://github.com/prashantghimire/sofifa-web-scraper/assets/4585039/e2f071ac-f81c-4f95-81ff-933b48cdea6f">
