### ISSUE TITLE
Scraping players nationality

### ISSUE THREAD

**Issue by dtaylor24** [prashantghimire/sofifa-web-scraper#18]
Hi

Is it possible to scrape the players Nationality? At the minute it scrapes the National team, but if they’re not in the team then it results in a blank entry.

Thanks

**Comment by prashantghimire** [comment]
@dtaylor24 dug a bit on this and apparently it's possible. there's 2 letter country code in the flag uri. have to translate that to full country name. a bit of work but possible. can't promise when but will update this thread once i add this feature. also, PRs are always welcome!
![image](https://github.com/prashantghimire/sofifa-web-scraper/assets/4585039/7070c54d-c532-4c6e-b002-b9d66faa429c)

**Comment by 210Labbasspur** [comment]
Hi @dtaylor24,

Yes, it is possible to scrape the players' Nationality. Whether you want to extract this data from a specific website or from any website, I can assist you with that. Feel free to check out my [Upwork profile](https://www.upwork.com/freelancers/~01de57a7da47612381?mp_source=share).

Thanks!
