### ISSUE TITLE
Add PlayerShortName

### ISSUE THREAD

**Issue by FabianZettl** [prashantghimire/sofifa-web-scraper#3]
Hey, is it possible to add a collumn with "playerShortname" for example:
L. Messi
J. Kimmich

This can be foudn on the very top of every sofifa player profile:
https://sofifa.com/player/243989/giovanni-zarfino/230025/

**Comment by prashantghimire** [comment]
Good idea, I will add that in the next release.

**Comment by FabianZettl** [comment]
Awesome, lvoe what you did there.
I use it as database for my efootball/PES Project

**Comment by ThaLeti** [comment]
Olá poderia me auxiliar como rodar esse script para conseguir pegar os dados atualizados ?

**Comment by prashantghimire** [comment]
@FabianZettl Short name is added now, you can check it out here:
https://github.com/prashantghimire/sofifa-web-scraper/blob/main/output/player_data_test.csv
To get the full file, you have to run `npm run download-all` locally.
![image](https://user-images.githubusercontent.com/4585039/232952858-04ee7d53-19f1-4cbd-9ed6-17a0c06d3ccd.png)

**Comment by prashantghimire** [comment]
@ThaLeti , please follow the instructions in README file and proceed.
