### ISSUE TITLE
What font should I be using to view the download all players csv provided in the readme? 

### ISSUE THREAD

**Issue by Novocastrian** [prashantghimire/sofifa-web-scraper#4]
Hello! 
I've noticed that the text in the CSV uses some characters that my computer cannot recognise. See below. 
![Screenshot 2023-06-09 214905](https://github.com/prashantghimire/sofifa-web-scraper/assets/4601813/b751c9f3-0ff4-48bb-93e1-1a62348109b1)

Is there a particular font or system language I should use to display correctly in English?

**Comment by prashantghimire** [comment]
@Novocastrian Does the texts show normally when you visit the sofifa website on the browser? It could be the issue with your CSV reader or systems language as well.

**Comment by Novocastrian** [comment]
Yeah, font is fine. E.g. Looking at Vinicius Junior in the Real Madrid team list:
https://sofifa.com/team/243/real-madrid/
![image](https://github.com/prashantghimire/sofifa-web-scraper/assets/4601813/b854298a-d386-4a3a-827e-7934b9894d99)
Excel language setting:
![image](https://github.com/prashantghimire/sofifa-web-scraper/assets/4601813/7c7d2dcb-25aa-4181-b09c-209b0e9210bd)

**Comment by Novocastrian** [comment]
This is my chrome browser's language settings:
![image](https://github.com/prashantghimire/sofifa-web-scraper/assets/4601813/e600f239-a148-4c08-8f20-29654bc35531)

**Comment by prashantghimire** [comment]
@Novocastrian sorry for late followup, were you able to resolve this? i believe this is not scraper issue, rather you editor or system language issue. It's hard to tell for me tbh.

**Comment by Novocastrian** [comment]
Hi, 

I'm sorry for not getting back to you sooner. 

You were close! It is an issue on the system side of things. Instead of opening the CSV directly with Excel:

1. Open a new spreadsheet (or a spreadsheet where you want to import the data to)
2. Data > From Text/CSV
![image](https://github.com/prashantghimire/sofifa-web-scraper/assets/4601813/fd57d57c-634f-4b0e-aefc-a4322c0aefe4)
3. Locate the CSV and click the Import button
![image](https://github.com/prashantghimire/sofifa-web-scraper/assets/4601813/310df796-c828-4d78-9a0d-6283453a4751)
4. Excel will preview the data. Observe that the preview renders the characters properly as UTF-8:
![image](https://github.com/prashantghimire/sofifa-web-scraper/assets/4601813/fb65a662-54fb-4f8d-935e-f1f8c6589fcd)
5. Click the Load button
6. Data is loaded
![image](https://github.com/prashantghimire/sofifa-web-scraper/assets/4601813/00a326e0-8fb9-41c6-ab71-70f60dec5666)

**Comment by prashantghimire** [comment]
Good to know, thanks for sharing!
