### ISSUE TITLE
Different points in time

### ISSUE THREAD

**Issue by oddsfinder** [prashantghimire/sofifa-web-scraper#5]
Hi! 

Would it be possible to set the time from which we scrape? For example all the player from FIFA20 instead of this year? 

and if so how can we do that? 

Many thanks

**Comment by prashantghimire** [comment]
Hi, it should be possible, but would be cumbersome since there's no one  "scraper schema" for multiple years of FIFA/EA FC. If you'd like to grab data for one specific year, you should be able to do so by changing the base url of the scraper.
