### ISSUE TITLE
Utilizzo

### ISSUE THREAD

**Issue by trivius86** [prashantghimire/sofifa-web-scraper#6]
C'è una guida specifica per scaricare i dati di sofifa piu dettagliatsa per capire l'utilizzo dello script

**Comment by prashantghimire** [comment]
Sorry, i tried google translate but still did not get it, may be something got lost in the translation. If you're looking for guide to download the full data, checkout readme.md file. I will soon update the most recent FC 24 data soon.

**Comment by prashantghimire** [comment]
Please reopen/file new issue if needed.
