### ISSUE TITLE
EA FC 24 Update

### ISSUE THREAD

**Issue by FabianZettl** [prashantghimire/sofifa-web-scraper#7]
Hey, scraping gives a lot of errors with ne FIFA24 / EAFC24 stats from sofifa

**Comment by prashantghimire** [comment]
Thanks for bringing into attention. Will spend some time this weekend to get a fix out.

**Comment by prashantghimire** [comment]
The code is updated with the fix now for EA FC 24. Please check the [test output csv](https://github.com/prashantghimire/sofifa-web-scraper/blob/main/output/player_data_test.csv) and validate.
