### ISSUE TITLE
Doesn't seem to work for the latest squad update

### ISSUE THREAD

**Issue by hannah389** [prashantghimire/sofifa-web-scraper#8]
I think SoFifa have changed a few things on their site because this no longer returns anything

**Comment by ArsendiMattia** [comment]
Did you get the following error?

> AxiosError: Request failed with status code 404

**Comment by prashantghimire** [comment]
I will look into this.

**Comment by prashantghimire** [comment]
the website started using cloudflare security for some time now and it seems to be only getting better (for them, worse for us). check this out. Check out #9 . I'm exploring some options but not feeling very hopeful.

**Comment by prashantghimire** [comment]
The cloudflare issue is resolved using humanoid and code is update to reflect latest sofifa update.

**Comment by prashantghimire** [comment]
Issue has been resolved in #9.
