### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by TheDarkCrown91** [prashantghimire/sofifa-web-scraper#9]
Hello,

since SOFIFA has integrated a Cloudflare Security on the site, the web scraper is not working anymore. Is there any possibility to fix it?

**Comment by Geffikk** [comment]
Hello,

The web scraper for SOFIFA is currently facing issues due to the implementation of Cloudflare Security on the site. Could we explore potential solutions to address this?

**Comment by prashantghimire** [comment]
hey @Geffikk and @TheDarkCrown91 , i looked into the issue and I agree with you. The main challenge is the Cloudflare security. The requests mostly fail except for some times. I'm looking into some options mentioned [here](https://scrapeops.io/web-scraping-playbook/how-to-bypass-cloudflare/). Also thinking about puppeteer as an alternative to direct usage of axios. But I have my doubts and the crawler will be super slow.

**Comment by prashantghimire** [comment]
I got some good results of bypassing cloudflare with humanoid-js. Another hurdle is recent change in the dom of sofifa. This is going to take a while but doable.

**Comment by Geffikk** [comment]
I've tried this humanoid-js but it doesn't work for me, but admittedly I've only tried it for about 15minutes 😄  I tried to work around it using the Google-cache site, but they also have bot detection

**Comment by prashantghimire** [comment]
humanoid has been consistently working for me. currently, i'm working on updating the code for sofifa's dom update. as a follow up, i will add capability to choose from different scrapper tools, like puppeteer, zenrows, etc.
[this article](https://www.zenrows.com/blog/bypass-cloudflare-nodejs#humanoid) shows good options for bypassing cloudflare.

**Comment by Geffikk** [comment]
I don't think zenrows is necessary because it's a really expensive option. I think it may be slower, but it should download the whole player data set. Can I ask if you have any ETA for update ?

**Comment by prashantghimire** [comment]
i had tried zenrows trial and seem to work faster than i expected, i believe they proxy the request around different ip. anyways, humanoid will be the primary crawler as of now, for those who want full proof solution and willing to pay, they could use zenrows. the code will be modular to support different crawler. i'm hoping to release a version with humanoid by this weekend.

**Comment by prashantghimire** [comment]
The cloudflare issue is resolved using humanoid and code is update to reflect latest sofifa update.

**Comment by Geffikk** [comment]
I will test it

**Comment by Geffikk** [comment]
Wonderful work ! May I have one wish for you ? Player-ids are being downloaded but if a new update comes then player_ids should be updated too, could you implement this before players  scraping (as before) ? And one more wish, can you implement json based scraping of older player stats versions ? 

E.g. the input would be this json and then, it will download all players stats from the specified dates into separate csv files. Thank you for your work!

```
{
    "24": {
        "dates": [
            "Feb 15, 2024",
            "Feb 22, 2024",
            "Mar 5, 2024",
            "Mar 7, 2024",
            "Mar 14, 2024",
            "Mar 20, 2024"
        ],
        "versions": [
            "240027",
            "240028",
            "240029",
            "240031",
            "240032",
            "240033"
        ]
    }
}
```

**Comment by prashantghimire** [comment]
@Geffikk it already has script to download the urls of all the players.
i made it easier to run it using npm script in this PR - #14.
the code can be easily extended to support old scans also, just need to pick a version from the options as shown in the attached screenshot.
you would need to do that around [this block of code](https://github.com/prashantghimire/sofifa-web-scraper/blob/63456972db6cc983bafbf0f0446436b87a5484c7/services/player-urls-loader.js#L18).
<img width="1454" alt="image" src="https://github.com/prashantghimire/sofifa-web-scraper/assets/4585039/c447a7ed-3332-4a4e-806d-7e9e9efa7e98">
I'm kinda busy for a week of two. you're welcome to PR.

**Comment by prashantghimire** [comment]
Closing the issue since the problem is resolved. Feel free to create a new issue for the above feature prefixed with "Feature Request - ".
